version: '3.8'

services:
  php:
    build: .
    container_name: spasample_php
    volumes:
      - .:/var/www
      - ./apache-config:/etc/apache2/sites-available
      - vendor-volumes:/var/www/vendor:delegated               #仮想サーバ側のみにファイル出力する設定
      - storage-framework-volumes:/var/www/storage/framework:delegated               #仮想サーバ側のみにファイル出力する設定
      - public-build-volumes:/var/www/public/build:delegated   #仮想サーバ側のみにファイル出力する設定
    ports:
      - "40614:80"
      - "5173:5173"  # Viteの開発サーバーポートを追加
    networks:
      - web

  db:
    image: mysql:8.0
    container_name: spasample_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: spasample
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: AYH4AZRptMxF
      MYSQL_USER: mwCys5btckJ
      MYSQL_PASSWORD: AYH4AZRptMxF
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: spasample_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: AYH4AZRptMxF
    ports:
      - "8081:80"
    networks:
      - web
      
volumes:
  db_data:
  vendor-volumes:             #仮想サーバ側のみにファイル出力する設定
  public-build-volumes:       #仮想サーバ側のみにファイル出力する設定
  storage-framework-volumes:  #仮想サーバ側のみにファイル出力する設定
networks:
  web:
    driver: bridge
